// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package bookingdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimExpiredBookings = `-- name: ClaimExpiredBookings :many
SELECT id, event_id, user_id, hold_id, qty, amount_paise, status, payment_deadline, intent_id, version, created_at, updated_at FROM booking.bookings
WHERE status = 'PENDING_PAYMENT' AND payment_deadline < now()
ORDER BY payment_deadline
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// The deadline job: pending bookings past their deadline, oldest first,
// locked so concurrent jobs (one per replica) take disjoint batches.
// Call inside a transaction that also moves them.
func (q *Queries) ClaimExpiredBookings(ctx context.Context, batch int32) ([]Booking, error) {
	rows, err := q.db.Query(ctx, claimExpiredBookings, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.HoldID,
			&i.Qty,
			&i.AmountPaise,
			&i.Status,
			&i.PaymentDeadline,
			&i.IntentID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO booking.bookings (id, event_id, user_id, hold_id, qty, amount_paise, payment_deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_id, user_id, hold_id, qty, amount_paise, status, payment_deadline, intent_id, version, created_at, updated_at
`

type CreateBookingParams struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	UserID          uuid.UUID
	HoldID          uuid.UUID
	Qty             int16
	AmountPaise     int64
	PaymentDeadline time.Time
}

// A booking starts PENDING_PAYMENT. hold_id is unique: a second booking for
// the same hold fails with a unique violation instead of being created.
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ID,
		arg.EventID,
		arg.UserID,
		arg.HoldID,
		arg.Qty,
		arg.AmountPaise,
		arg.PaymentDeadline,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.HoldID,
		&i.Qty,
		&i.AmountPaise,
		&i.Status,
		&i.PaymentDeadline,
		&i.IntentID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, event_id, user_id, hold_id, qty, amount_paise, status, payment_deadline, intent_id, version, created_at, updated_at FROM booking.bookings WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.HoldID,
		&i.Qty,
		&i.AmountPaise,
		&i.Status,
		&i.PaymentDeadline,
		&i.IntentID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByHold = `-- name: GetBookingByHold :one
SELECT id, event_id, user_id, hold_id, qty, amount_paise, status, payment_deadline, intent_id, version, created_at, updated_at FROM booking.bookings WHERE hold_id = $1
`

func (q *Queries) GetBookingByHold(ctx context.Context, holdID uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByHold, holdID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.HoldID,
		&i.Qty,
		&i.AmountPaise,
		&i.Status,
		&i.PaymentDeadline,
		&i.IntentID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingForUpdate = `-- name: GetBookingForUpdate :one
SELECT id, event_id, user_id, hold_id, qty, amount_paise, status, payment_deadline, intent_id, version, created_at, updated_at FROM booking.bookings WHERE id = $1 FOR UPDATE
`

// The saga locks the booking while it decides, so two deliveries of events
// for one booking cannot decide at once.
func (q *Queries) GetBookingForUpdate(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingForUpdate, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.HoldID,
		&i.Qty,
		&i.AmountPaise,
		&i.Status,
		&i.PaymentDeadline,
		&i.IntentID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingForUser = `-- name: GetBookingForUser :one
SELECT id, event_id, user_id, hold_id, qty, amount_paise, status, payment_deadline, intent_id, version, created_at, updated_at FROM booking.bookings WHERE id = $1 AND user_id = $2
`

type GetBookingForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Owner-only read: another user's booking is "not found", never "forbidden",
// so booking IDs cannot be probed.
func (q *Queries) GetBookingForUser(ctx context.Context, arg GetBookingForUserParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingForUser, arg.ID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.HoldID,
		&i.Qty,
		&i.AmountPaise,
		&i.Status,
		&i.PaymentDeadline,
		&i.IntentID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPerUserLimit = `-- name: GetPerUserLimit :one
SELECT per_user_limit FROM booking.events WHERE id = $1
`

func (q *Queries) GetPerUserLimit(ctx context.Context, id uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, getPerUserLimit, id)
	var per_user_limit int16
	err := row.Scan(&per_user_limit)
	return per_user_limit, err
}

const setBookingIntent = `-- name: SetBookingIntent :one
UPDATE booking.bookings
SET intent_id = $1, updated_at = now()
WHERE id = $2 AND (intent_id IS NULL OR intent_id = $1)
RETURNING id, event_id, user_id, hold_id, qty, amount_paise, status, payment_deadline, intent_id, version, created_at, updated_at
`

type SetBookingIntentParams struct {
	IntentID uuid.NullUUID
	ID       uuid.UUID
}

// Records payment-svc's intent once; a retry with the same intent is a no-op,
// a different one is refused (no row).
func (q *Queries) SetBookingIntent(ctx context.Context, arg SetBookingIntentParams) (Booking, error) {
	row := q.db.QueryRow(ctx, setBookingIntent, arg.IntentID, arg.ID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.HoldID,
		&i.Qty,
		&i.AmountPaise,
		&i.Status,
		&i.PaymentDeadline,
		&i.IntentID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionBooking = `-- name: TransitionBooking :one
UPDATE booking.bookings
SET status = $1, version = version + 1, updated_at = now()
WHERE id = $2 AND status = $3
RETURNING id, event_id, user_id, hold_id, qty, amount_paise, status, payment_deadline, intent_id, version, created_at, updated_at
`

type TransitionBookingParams struct {
	ToStatus   string
	ID         uuid.UUID
	FromStatus string
}

// Compare-and-set: moves the booking only if it is still in the expected
// status. No row means another actor moved it first (or it does not exist);
// the caller re-reads and decides. The trigger refuses invalid moves.
func (q *Queries) TransitionBooking(ctx context.Context, arg TransitionBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, transitionBooking, arg.ToStatus, arg.ID, arg.FromStatus)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.HoldID,
		&i.Qty,
		&i.AmountPaise,
		&i.Status,
		&i.PaymentDeadline,
		&i.IntentID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
