// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package bookingdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const beginIdempotentRequest = `-- name: BeginIdempotentRequest :one
INSERT INTO booking.idempotency_keys (user_id, idem_key, request_hash)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, idem_key) DO NOTHING
RETURNING user_id, idem_key, request_hash, status, booking_id, response_code, response_body, created_at, updated_at
`

type BeginIdempotentRequestParams struct {
	UserID      uuid.UUID
	IdemKey     string
	RequestHash []byte
}

// Claims a key for a request. No row means the key exists already: read it
// with GetIdempotencyKey and replay, wait, or refuse a different request.
func (q *Queries) BeginIdempotentRequest(ctx context.Context, arg BeginIdempotentRequestParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, beginIdempotentRequest, arg.UserID, arg.IdemKey, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.IdemKey,
		&i.RequestHash,
		&i.Status,
		&i.BookingID,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeIdempotentRequest = `-- name: CompleteIdempotentRequest :one
UPDATE booking.idempotency_keys
SET status = 'COMPLETED', booking_id = $1, response_code = $2,
    response_body = $3, updated_at = now()
WHERE user_id = $4 AND idem_key = $5 AND status = 'IN_PROGRESS'
RETURNING user_id, idem_key, request_hash, status, booking_id, response_code, response_body, created_at, updated_at
`

type CompleteIdempotentRequestParams struct {
	BookingID    uuid.NullUUID
	ResponseCode pgtype.Int2
	ResponseBody []byte
	UserID       uuid.UUID
	IdemKey      string
}

// Stores the response once; only an IN_PROGRESS key can complete.
func (q *Queries) CompleteIdempotentRequest(ctx context.Context, arg CompleteIdempotentRequestParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, completeIdempotentRequest,
		arg.BookingID,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.UserID,
		arg.IdemKey,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.IdemKey,
		&i.RequestHash,
		&i.Status,
		&i.BookingID,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIdempotencyKeysBefore = `-- name: DeleteIdempotencyKeysBefore :execrows
DELETE FROM booking.idempotency_keys WHERE created_at < $1
`

// Keys are kept for 24 hours (design doc 9.5); retries come within minutes.
func (q *Queries) DeleteIdempotencyKeysBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdempotencyKeysBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT user_id, idem_key, request_hash, status, booking_id, response_code, response_body, created_at, updated_at FROM booking.idempotency_keys WHERE user_id = $1 AND idem_key = $2
`

type GetIdempotencyKeyParams struct {
	UserID  uuid.UUID
	IdemKey string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.IdemKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.IdemKey,
		&i.RequestHash,
		&i.Status,
		&i.BookingID,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
