// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messaging.sql

package bookingdb

import (
	"context"

	"github.com/google/uuid"
)

const claimUnpublishedEvents = `-- name: ClaimUnpublishedEvents :many
SELECT id, event_id, topic, aggregate_id, event_type, payload, headers, created_at, published_at FROM booking.outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// The relay's batch, in commit order, locked so a second relay (during a
// leadership handover) skips rather than duplicates them.
func (q *Queries) ClaimUnpublishedEvents(ctx context.Context, batch int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedEvents, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Topic,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Headers,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO booking.outbox (event_id, topic, aggregate_id, event_type, payload, headers)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOutboxEventParams struct {
	EventID     uuid.UUID
	Topic       string
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
	Headers     []byte
}

// Write in the same transaction as the state change the event describes.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.EventID,
		arg.Topic,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Headers,
	)
	return err
}

const markEventsPublished = `-- name: MarkEventsPublished :exec
UPDATE booking.outbox SET published_at = now() WHERE id = ANY($1::bigint[]) AND published_at IS NULL
`

func (q *Queries) MarkEventsPublished(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markEventsPublished, ids)
	return err
}

const recordProcessedMessage = `-- name: RecordProcessedMessage :execrows
INSERT INTO booking.processed_messages (consumer, message_id)
VALUES ($1, $2)
ON CONFLICT (consumer, message_id) DO NOTHING
`

type RecordProcessedMessageParams struct {
	Consumer  string
	MessageID string
}

// Returns 1 the first time a consumer sees a message and 0 for a redelivery.
// Run in the same transaction as the message's effect.
func (q *Queries) RecordProcessedMessage(ctx context.Context, arg RecordProcessedMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordProcessedMessage, arg.Consumer, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
