// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bookingdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID              uuid.UUID
	EventID         uuid.UUID
	UserID          uuid.UUID
	HoldID          uuid.UUID
	Qty             int16
	AmountPaise     int64
	Status          string
	PaymentDeadline time.Time
	IntentID        uuid.NullUUID
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Event struct {
	ID                   uuid.UUID
	Name                 string
	SaleOpensAt          time.Time
	VerifiedWindowEndsAt pgtype.Timestamptz
	AgentLockoutEndsAt   pgtype.Timestamptz
	PerUserLimit         int16
	UnitPricePaise       int64
	Status               string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type EventInventory struct {
	EventID   uuid.UUID
	Capacity  int32
	Sold      int32
	UpdatedAt time.Time
}

type IdempotencyKey struct {
	UserID       uuid.UUID
	IdemKey      string
	RequestHash  []byte
	Status       string
	BookingID    uuid.NullUUID
	ResponseCode pgtype.Int2
	ResponseBody []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type OutboxEvent struct {
	ID          int64
	EventID     uuid.UUID
	Topic       string
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
	Headers     []byte
	CreatedAt   time.Time
	PublishedAt pgtype.Timestamptz
}

type ProcessedMessage struct {
	Consumer    string
	MessageID   string
	ProcessedAt time.Time
}

type UserEventPurchase struct {
	EventID   uuid.UUID
	UserID    uuid.UUID
	Qty       int16
	UpdatedAt time.Time
}
