// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshot.sql

package bookingdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const snapshotEventInventory = `-- name: SnapshotEventInventory :one

SELECT i.capacity, i.sold, e.per_user_limit
FROM booking.event_inventory i
JOIN booking.events e ON e.id = i.event_id
WHERE i.event_id = $1
`

type SnapshotEventInventoryRow struct {
	Capacity     int32
	Sold         int32
	PerUserLimit int16
}

// What an event's inventory must be, by the records (runbook RB-2, task
// 5.3). Read together in one repeatable-read transaction (InventorySnapshot).
func (q *Queries) SnapshotEventInventory(ctx context.Context, eventID uuid.UUID) (SnapshotEventInventoryRow, error) {
	row := q.db.QueryRow(ctx, snapshotEventInventory, eventID)
	var i SnapshotEventInventoryRow
	err := row.Scan(&i.Capacity, &i.Sold, &i.PerUserLimit)
	return i, err
}

const snapshotPendingBookings = `-- name: SnapshotPendingBookings :many
SELECT hold_id, user_id, qty, payment_deadline
FROM booking.bookings
WHERE event_id = $1 AND status = 'PENDING_PAYMENT'
ORDER BY created_at, id
`

type SnapshotPendingBookingsRow struct {
	HoldID          uuid.UUID
	UserID          uuid.UUID
	Qty             int16
	PaymentDeadline time.Time
}

// Bookings waiting for payment still hold their units (a PAYING hold).
func (q *Queries) SnapshotPendingBookings(ctx context.Context, eventID uuid.UUID) ([]SnapshotPendingBookingsRow, error) {
	rows, err := q.db.Query(ctx, snapshotPendingBookings, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SnapshotPendingBookingsRow{}
	for rows.Next() {
		var i SnapshotPendingBookingsRow
		if err := rows.Scan(
			&i.HoldID,
			&i.UserID,
			&i.Qty,
			&i.PaymentDeadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotPurchases = `-- name: SnapshotPurchases :many
SELECT user_id, qty
FROM booking.user_event_purchases
WHERE event_id = $1 AND qty > 0
`

type SnapshotPurchasesRow struct {
	UserID uuid.UUID
	Qty    int16
}

// Units each user bought, as the final guard counted them.
func (q *Queries) SnapshotPurchases(ctx context.Context, eventID uuid.UUID) ([]SnapshotPurchasesRow, error) {
	rows, err := q.db.Query(ctx, snapshotPurchases, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SnapshotPurchasesRow{}
	for rows.Next() {
		var i SnapshotPurchasesRow
		if err := rows.Scan(&i.UserID, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
