-- +goose Up
-- auth-svc's schema (design doc 8.1): users identified by a verified phone,
-- one-time codes, and rotating refresh tokens. No phone number, code or
-- refresh token is ever stored in the clear: phones as an HMAC (plus the last
-- four digits for display), codes and tokens as hashes.
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE auth.users (
  id                uuid        PRIMARY KEY,          -- UUIDv7, generated by auth-svc
  phone_hmac        bytea       NOT NULL UNIQUE,      -- HMAC-SHA256(pepper, phone): lookup without storing the number
  phone_last4       char(4)     NOT NULL,
  phone_verified_at timestamptz,
  role              text        NOT NULL DEFAULT 'BUYER' CHECK (role IN ('BUYER', 'AGENT', 'ADMIN')),
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- One-time codes. A phone's latest unconsumed challenge is the one a code is
-- checked against; each wrong guess counts, and five end the challenge.
CREATE TABLE auth.otp_challenges (
  id          uuid        PRIMARY KEY,                -- UUIDv7
  phone_hmac  bytea       NOT NULL,
  code_hash   bytea       NOT NULL,                   -- HMAC(pepper, id || code): never the code itself
  attempts    smallint    NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  expires_at  timestamptz NOT NULL,
  consumed_at timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX otp_challenges_phone_idx ON auth.otp_challenges (phone_hmac, created_at DESC);

-- Refresh tokens rotate on every use. Each belongs to a family (one login);
-- presenting a token that was already replaced means it was stolen or
-- replayed, and the whole family is revoked.
CREATE TABLE auth.refresh_tokens (
  token_hash  bytea       PRIMARY KEY,                -- SHA-256 of the opaque token
  user_id     uuid        NOT NULL REFERENCES auth.users (id),
  family_id   uuid        NOT NULL,
  replaced_by bytea,
  revoked_at  timestamptz,
  expires_at  timestamptz NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX refresh_tokens_family_idx ON auth.refresh_tokens (family_id);

-- +goose Down
DROP SCHEMA IF EXISTS auth CASCADE;
