-- +goose Up
-- Payment schema (owned by payment-svc, Phase 3): payment intents and their
-- state machine, the PSP's orders, received webhooks, a double-entry ledger,
-- and the outbox and processed-message tables every service schema has.
-- IDs are UUIDv7 generated by the application.
CREATE SCHEMA IF NOT EXISTS payment;

-- One intent per booking (invariant I2: at most one captured payment per
-- booking). Its status follows design doc 7.3; the trigger below refuses any
-- other move.
CREATE TABLE payment.payment_intents (
  id             uuid        PRIMARY KEY,
  booking_id     uuid        NOT NULL UNIQUE,
  amount_paise   bigint      NOT NULL CHECK (amount_paise > 0), -- integer paise, never float
  currency       char(3)     NOT NULL DEFAULT 'INR',
  status         text        NOT NULL DEFAULT 'CREATED'
                 CHECK (status IN ('CREATED', 'CAPTURED', 'FAILED', 'EXPIRED', 'REFUND_PENDING', 'REFUNDED')),
  psp_order_id   text        UNIQUE,
  psp_payment_id text        UNIQUE,
  checkout_url   text,
  expires_at     timestamptz NOT NULL,
  version        integer     NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  CHECK (status NOT IN ('CAPTURED', 'REFUND_PENDING', 'REFUNDED') OR psp_payment_id IS NOT NULL)
);

-- Intents that may be stuck waiting for a webhook (status polling).
CREATE INDEX payment_intents_open_idx ON payment.payment_intents (created_at)
  WHERE status = 'CREATED';

-- +goose StatementBegin
CREATE FUNCTION payment.check_intent_transition() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status = OLD.status THEN
    RETURN NEW;
  END IF;
  IF (OLD.status, NEW.status) IN (
       ('CREATED',        'CAPTURED'),
       ('CREATED',        'FAILED'),
       ('CREATED',        'EXPIRED'),
       ('FAILED',         'CAPTURED'),  -- a later attempt on the same order succeeded
       ('EXPIRED',        'CAPTURED'),  -- a capture reported late: money moved, so it wins
       ('CAPTURED',       'REFUND_PENDING'),
       ('REFUND_PENDING', 'REFUNDED')) THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'payment intent %: % -> % is not a valid transition', OLD.id, OLD.status, NEW.status
    USING ERRCODE = 'check_violation';
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER payment_intents_status_transition
  BEFORE UPDATE OF status ON payment.payment_intents
  FOR EACH ROW EXECUTE FUNCTION payment.check_intent_transition();

-- The PSP's order for an intent, created with the intent's ID as the PSP's
-- idempotency key, so a retried create returns the same order.
CREATE TABLE payment.psp_orders (
  psp_order_id text        PRIMARY KEY,
  intent_id    uuid        NOT NULL UNIQUE REFERENCES payment.payment_intents (id),
  amount_paise bigint      NOT NULL CHECK (amount_paise > 0),
  checkout_url text        NOT NULL,
  expires_at   timestamptz NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- Every webhook the PSP sent, once: the PSP's event ID is the primary key,
-- so a duplicate delivery inserts nothing and is acknowledged without effect.
CREATE TABLE payment.webhook_events (
  psp_event_id text        PRIMARY KEY,
  event_type   text        NOT NULL,
  psp_order_id text,
  payload      jsonb       NOT NULL,
  received_at  timestamptz NOT NULL DEFAULT now()
);

-- Double-entry ledger: every money movement is one transaction (txn_id) of
-- entries whose debits equal its credits; the constraint trigger below checks
-- it at commit.
--   capture:    debit psp_receivable,        credit unearned_revenue:<event>
--   refund:     debit unearned_revenue:<e>,  credit psp_receivable
--   settlement: debit bank,                  credit psp_receivable
CREATE TABLE payment.ledger_entries (
  id           bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  txn_id       uuid        NOT NULL,
  account      text        NOT NULL CHECK (account ~ '^(psp_receivable|bank|unearned_revenue:[0-9a-f-]{36})$'),
  direction    char(1)     NOT NULL CHECK (direction IN ('D', 'C')),
  amount_paise bigint      NOT NULL CHECK (amount_paise > 0),
  intent_id    uuid        NOT NULL REFERENCES payment.payment_intents (id),
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ledger_entries_txn_idx ON payment.ledger_entries (txn_id);
CREATE INDEX ledger_entries_intent_idx ON payment.ledger_entries (intent_id);

-- +goose StatementBegin
CREATE FUNCTION payment.check_ledger_balanced() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  imbalance bigint;
BEGIN
  SELECT coalesce(sum(CASE direction WHEN 'D' THEN amount_paise ELSE -amount_paise END), 0)
    INTO imbalance
    FROM payment.ledger_entries
   WHERE txn_id = NEW.txn_id;
  IF imbalance <> 0 THEN
    RAISE EXCEPTION 'ledger transaction % is unbalanced by % paise', NEW.txn_id, imbalance
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NULL;
END;
$$;
-- +goose StatementEnd

-- Deferred to COMMIT, so a transaction can insert its debit and credit in
-- any order; a transaction that ends unbalanced is rolled back.
CREATE CONSTRAINT TRIGGER ledger_entries_balanced
  AFTER INSERT OR UPDATE ON payment.ledger_entries
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION payment.check_ledger_balanced();

-- The transactional outbox and processed messages, as in the booking schema.
CREATE TABLE payment.outbox (
  id           bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  event_id     uuid        NOT NULL UNIQUE,
  topic        text        NOT NULL,
  aggregate_id uuid        NOT NULL, -- the Kafka message key (the booking ID)
  event_type   text        NOT NULL,
  payload      bytea       NOT NULL,
  headers      jsonb       NOT NULL DEFAULT '{}',
  created_at   timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz
);
CREATE INDEX outbox_unpublished_idx ON payment.outbox (id) WHERE published_at IS NULL;

CREATE TABLE payment.processed_messages (
  consumer     text        NOT NULL,
  message_id   text        NOT NULL,
  processed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (consumer, message_id)
);

-- +goose Down
DROP SCHEMA IF EXISTS payment CASCADE;
