// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intents.sql

package paymentdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachOrder = `-- name: AttachOrder :one
UPDATE payment.payment_intents
SET psp_order_id = $1, checkout_url = $2, updated_at = now()
WHERE id = $3 AND (psp_order_id IS NULL OR psp_order_id = $1)
RETURNING id, booking_id, amount_paise, currency, status, psp_order_id, psp_payment_id, checkout_url, expires_at, version, created_at, updated_at, event_id
`

type AttachOrderParams struct {
	PspOrderID  pgtype.Text
	CheckoutUrl pgtype.Text
	ID          uuid.UUID
}

// Records the PSP's order once; repeating it with the same order is a no-op,
// a different one is refused (no row).
func (q *Queries) AttachOrder(ctx context.Context, arg AttachOrderParams) (Intent, error) {
	row := q.db.QueryRow(ctx, attachOrder, arg.PspOrderID, arg.CheckoutUrl, arg.ID)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountPaise,
		&i.Currency,
		&i.Status,
		&i.PspOrderID,
		&i.PspPaymentID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}

const captureIntent = `-- name: CaptureIntent :one
UPDATE payment.payment_intents
SET status = 'CAPTURED', psp_payment_id = $1, version = version + 1, updated_at = now()
WHERE id = $2 AND status IN ('CREATED', 'FAILED', 'EXPIRED')
RETURNING id, booking_id, amount_paise, currency, status, psp_order_id, psp_payment_id, checkout_url, expires_at, version, created_at, updated_at, event_id
`

type CaptureIntentParams struct {
	PspPaymentID pgtype.Text
	ID           uuid.UUID
}

// Compare-and-set to CAPTURED from any status that a capture may follow
// (a capture always wins: money moved). No row: already captured or later.
func (q *Queries) CaptureIntent(ctx context.Context, arg CaptureIntentParams) (Intent, error) {
	row := q.db.QueryRow(ctx, captureIntent, arg.PspPaymentID, arg.ID)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountPaise,
		&i.Currency,
		&i.Status,
		&i.PspOrderID,
		&i.PspPaymentID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}

const claimOpenIntents = `-- name: ClaimOpenIntents :many
SELECT id, booking_id, amount_paise, currency, status, psp_order_id, psp_payment_id, checkout_url, expires_at, version, created_at, updated_at, event_id FROM payment.payment_intents
WHERE status = 'CREATED' AND created_at < $1 AND psp_order_id IS NOT NULL
ORDER BY created_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimOpenIntentsParams struct {
	CreatedBefore time.Time
	Batch         int32
}

// Status polling: intents still CREATED after a while, possibly because a
// webhook was lost. Locked so concurrent pollers take disjoint batches.
func (q *Queries) ClaimOpenIntents(ctx context.Context, arg ClaimOpenIntentsParams) ([]Intent, error) {
	rows, err := q.db.Query(ctx, claimOpenIntents, arg.CreatedBefore, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Intent{}
	for rows.Next() {
		var i Intent
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.AmountPaise,
			&i.Currency,
			&i.Status,
			&i.PspOrderID,
			&i.PspPaymentID,
			&i.CheckoutUrl,
			&i.ExpiresAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createIntent = `-- name: CreateIntent :one
INSERT INTO payment.payment_intents (id, booking_id, event_id, amount_paise, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (booking_id) DO NOTHING
RETURNING id, booking_id, amount_paise, currency, status, psp_order_id, psp_payment_id, checkout_url, expires_at, version, created_at, updated_at, event_id
`

type CreateIntentParams struct {
	ID          uuid.UUID
	BookingID   uuid.UUID
	EventID     uuid.NullUUID
	AmountPaise int64
	ExpiresAt   time.Time
}

// One intent per booking: a second create for the same booking inserts
// nothing (no row), and the caller reads the existing one.
func (q *Queries) CreateIntent(ctx context.Context, arg CreateIntentParams) (Intent, error) {
	row := q.db.QueryRow(ctx, createIntent,
		arg.ID,
		arg.BookingID,
		arg.EventID,
		arg.AmountPaise,
		arg.ExpiresAt,
	)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountPaise,
		&i.Currency,
		&i.Status,
		&i.PspOrderID,
		&i.PspPaymentID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}

const getIntent = `-- name: GetIntent :one
SELECT id, booking_id, amount_paise, currency, status, psp_order_id, psp_payment_id, checkout_url, expires_at, version, created_at, updated_at, event_id FROM payment.payment_intents WHERE id = $1
`

func (q *Queries) GetIntent(ctx context.Context, id uuid.UUID) (Intent, error) {
	row := q.db.QueryRow(ctx, getIntent, id)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountPaise,
		&i.Currency,
		&i.Status,
		&i.PspOrderID,
		&i.PspPaymentID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}

const getIntentByBooking = `-- name: GetIntentByBooking :one
SELECT id, booking_id, amount_paise, currency, status, psp_order_id, psp_payment_id, checkout_url, expires_at, version, created_at, updated_at, event_id FROM payment.payment_intents WHERE booking_id = $1
`

func (q *Queries) GetIntentByBooking(ctx context.Context, bookingID uuid.UUID) (Intent, error) {
	row := q.db.QueryRow(ctx, getIntentByBooking, bookingID)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountPaise,
		&i.Currency,
		&i.Status,
		&i.PspOrderID,
		&i.PspPaymentID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}

const getIntentByOrder = `-- name: GetIntentByOrder :one
SELECT id, booking_id, amount_paise, currency, status, psp_order_id, psp_payment_id, checkout_url, expires_at, version, created_at, updated_at, event_id FROM payment.payment_intents WHERE psp_order_id = $1
`

func (q *Queries) GetIntentByOrder(ctx context.Context, pspOrderID pgtype.Text) (Intent, error) {
	row := q.db.QueryRow(ctx, getIntentByOrder, pspOrderID)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountPaise,
		&i.Currency,
		&i.Status,
		&i.PspOrderID,
		&i.PspPaymentID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}

const insertPSPOrder = `-- name: InsertPSPOrder :exec
INSERT INTO payment.psp_orders (psp_order_id, intent_id, amount_paise, checkout_url, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (psp_order_id) DO NOTHING
`

type InsertPSPOrderParams struct {
	PspOrderID  string
	IntentID    uuid.UUID
	AmountPaise int64
	CheckoutUrl string
	ExpiresAt   time.Time
}

func (q *Queries) InsertPSPOrder(ctx context.Context, arg InsertPSPOrderParams) error {
	_, err := q.db.Exec(ctx, insertPSPOrder,
		arg.PspOrderID,
		arg.IntentID,
		arg.AmountPaise,
		arg.CheckoutUrl,
		arg.ExpiresAt,
	)
	return err
}

const transitionIntent = `-- name: TransitionIntent :one
UPDATE payment.payment_intents
SET status = $1, version = version + 1, updated_at = now()
WHERE id = $2 AND status = $3
RETURNING id, booking_id, amount_paise, currency, status, psp_order_id, psp_payment_id, checkout_url, expires_at, version, created_at, updated_at, event_id
`

type TransitionIntentParams struct {
	ToStatus   string
	ID         uuid.UUID
	FromStatus string
}

// Compare-and-set for the other moves; the trigger refuses invalid ones.
func (q *Queries) TransitionIntent(ctx context.Context, arg TransitionIntentParams) (Intent, error) {
	row := q.db.QueryRow(ctx, transitionIntent, arg.ToStatus, arg.ID, arg.FromStatus)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountPaise,
		&i.Currency,
		&i.Status,
		&i.PspOrderID,
		&i.PspPaymentID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}
