// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messaging.sql

package paymentdb

import (
	"context"

	"github.com/google/uuid"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO payment.outbox (event_id, topic, aggregate_id, event_type, payload, headers)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOutboxEventParams struct {
	EventID     uuid.UUID
	Topic       string
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
	Headers     []byte
}

// Write in the same transaction as the state change the event describes.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.EventID,
		arg.Topic,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Headers,
	)
	return err
}

const recordProcessedMessage = `-- name: RecordProcessedMessage :execrows
INSERT INTO payment.processed_messages (consumer, message_id)
VALUES ($1, $2)
ON CONFLICT (consumer, message_id) DO NOTHING
`

type RecordProcessedMessageParams struct {
	Consumer  string
	MessageID string
}

// 1 the first time a consumer sees a message, 0 for a redelivery.
func (q *Queries) RecordProcessedMessage(ctx context.Context, arg RecordProcessedMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordProcessedMessage, arg.Consumer, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
