// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package paymentdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Intent struct {
	ID           uuid.UUID
	BookingID    uuid.UUID
	AmountPaise  int64
	Currency     string
	Status       string
	PspOrderID   pgtype.Text
	PspPaymentID pgtype.Text
	CheckoutUrl  pgtype.Text
	ExpiresAt    time.Time
	Version      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EventID      uuid.NullUUID
	PolledAt     pgtype.Timestamptz
	TraceContext []byte
}

type LedgerEntry struct {
	ID          int64
	TxnID       uuid.UUID
	Account     string
	Direction   string
	AmountPaise int64
	IntentID    uuid.UUID
	CreatedAt   time.Time
}

type OutboxEvent struct {
	ID          int64
	EventID     uuid.UUID
	Topic       string
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
	Headers     []byte
	CreatedAt   time.Time
	PublishedAt pgtype.Timestamptz
}

type PSPOrder struct {
	PspOrderID  string
	IntentID    uuid.UUID
	AmountPaise int64
	CheckoutUrl string
	ExpiresAt   time.Time
	CreatedAt   time.Time
}

type ProcessedMessage struct {
	Consumer    string
	MessageID   string
	ProcessedAt time.Time
}

type WebhookEvent struct {
	PspEventID string
	EventType  string
	PspOrderID pgtype.Text
	Payload    []byte
	ReceivedAt time.Time
}
