// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package paymentdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const capturesBookedBetween = `-- name: CapturesBookedBetween :many
SELECT DISTINCT i.id, i.psp_payment_id, i.amount_paise
FROM payment.ledger_entries l
JOIN payment.payment_intents i ON i.id = l.intent_id
WHERE l.account = 'psp_receivable' AND l.direction = 'D'
  AND l.created_at >= $1 AND l.created_at < $2
`

type CapturesBookedBetweenParams struct {
	FromTime time.Time
	ToTime   time.Time
}

type CapturesBookedBetweenRow struct {
	ID           uuid.UUID
	PspPaymentID pgtype.Text
	AmountPaise  int64
}

// Intents whose capture was booked in the ledger in [from, to): what the
// provider's settlement report must also contain (reconciliation, design
// doc 9.9). A capture is the debit of psp_receivable.
func (q *Queries) CapturesBookedBetween(ctx context.Context, arg CapturesBookedBetweenParams) ([]CapturesBookedBetweenRow, error) {
	rows, err := q.db.Query(ctx, capturesBookedBetween, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CapturesBookedBetweenRow{}
	for rows.Next() {
		var i CapturesBookedBetweenRow
		if err := rows.Scan(&i.ID, &i.PspPaymentID, &i.AmountPaise); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stuckRefunds = `-- name: StuckRefunds :many
SELECT id, booking_id, amount_paise, currency, status, psp_order_id, psp_payment_id, checkout_url, expires_at, version, created_at, updated_at, event_id, polled_at, trace_context FROM payment.payment_intents
WHERE status = 'REFUND_PENDING' AND updated_at < $1
ORDER BY updated_at
LIMIT $2
`

type StuckRefundsParams struct {
	Before time.Time
	Batch  int32
}

// Refunds requested (REFUND_PENDING) and still not completed after a while:
// the provider call may never have succeeded.
func (q *Queries) StuckRefunds(ctx context.Context, arg StuckRefundsParams) ([]Intent, error) {
	rows, err := q.db.Query(ctx, stuckRefunds, arg.Before, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Intent{}
	for rows.Next() {
		var i Intent
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.AmountPaise,
			&i.Currency,
			&i.Status,
			&i.PspOrderID,
			&i.PspPaymentID,
			&i.CheckoutUrl,
			&i.ExpiresAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventID,
			&i.PolledAt,
			&i.TraceContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
