// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks_ledger.sql

package paymentdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountBalance = `-- name: AccountBalance :one
SELECT coalesce(sum(CASE direction WHEN 'D' THEN amount_paise ELSE -amount_paise END), 0)::bigint AS balance
FROM payment.ledger_entries WHERE account = $1
`

// Debits minus credits for one account.
func (q *Queries) AccountBalance(ctx context.Context, account string) (int64, error) {
	row := q.db.QueryRow(ctx, accountBalance, account)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO payment.ledger_entries (txn_id, account, direction, amount_paise, intent_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertLedgerEntryParams struct {
	TxnID       uuid.UUID
	Account     string
	Direction   string
	AmountPaise int64
	IntentID    uuid.UUID
}

// Insert every entry of one txn_id in the same database transaction: the
// deferred trigger refuses, at commit, a transaction whose debits and
// credits differ.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.TxnID,
		arg.Account,
		arg.Direction,
		arg.AmountPaise,
		arg.IntentID,
	)
	return err
}

const recordWebhook = `-- name: RecordWebhook :execrows
INSERT INTO payment.webhook_events (psp_event_id, event_type, psp_order_id, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (psp_event_id) DO NOTHING
`

type RecordWebhookParams struct {
	PspEventID string
	EventType  string
	PspOrderID pgtype.Text
	Payload    []byte
}

// 1 for a webhook seen for the first time, 0 for a duplicate delivery.
// Run in the same transaction as the webhook's effect.
func (q *Queries) RecordWebhook(ctx context.Context, arg RecordWebhookParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWebhook,
		arg.PspEventID,
		arg.EventType,
		arg.PspOrderID,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
