// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OTPChallenge struct {
	ID         uuid.UUID
	PhoneHmac  []byte
	CodeHash   []byte
	Attempts   int16
	ExpiresAt  time.Time
	ConsumedAt pgtype.Timestamptz
	CreatedAt  time.Time
}

type RefreshToken struct {
	TokenHash  []byte
	UserID     uuid.UUID
	FamilyID   uuid.UUID
	ReplacedBy []byte
	RevokedAt  pgtype.Timestamptz
	ExpiresAt  time.Time
	CreatedAt  time.Time
}

type User struct {
	ID              uuid.UUID
	PhoneHmac       []byte
	PhoneLast4      string
	PhoneVerifiedAt pgtype.Timestamptz
	Role            string
	CreatedAt       time.Time
}
