// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeChallenge = `-- name: ConsumeChallenge :execrows
UPDATE auth.otp_challenges SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
`

// A correct code is used once.
func (q *Queries) ConsumeChallenge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeChallenge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertChallenge = `-- name: InsertChallenge :exec
INSERT INTO auth.otp_challenges (id, phone_hmac, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertChallengeParams struct {
	ID        uuid.UUID
	PhoneHmac []byte
	CodeHash  []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertChallenge(ctx context.Context, arg InsertChallengeParams) error {
	_, err := q.db.Exec(ctx, insertChallenge,
		arg.ID,
		arg.PhoneHmac,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const lockPhone = `-- name: LockPhone :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Serialises OTP requests for one phone within the caller's transaction, so
// the rate limit cannot be raced.
func (q *Queries) LockPhone(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockPhone, key)
	return err
}

const recentChallenges = `-- name: RecentChallenges :one
SELECT count(*)::int AS sent,
       coalesce(min(created_at), 'epoch'::timestamptz)::timestamptz AS oldest,
       coalesce(max(created_at), 'epoch'::timestamptz)::timestamptz AS latest
FROM auth.otp_challenges
WHERE phone_hmac = $1 AND created_at > $2
`

type RecentChallengesParams struct {
	PhoneHmac []byte
	Since     time.Time
}

type RecentChallengesRow struct {
	Sent   int32
	Oldest time.Time
	Latest time.Time
}

// How many codes the phone was sent since a time, and when the first and
// the last of them were (the epoch when none).
func (q *Queries) RecentChallenges(ctx context.Context, arg RecentChallengesParams) (RecentChallengesRow, error) {
	row := q.db.QueryRow(ctx, recentChallenges, arg.PhoneHmac, arg.Since)
	var i RecentChallengesRow
	err := row.Scan(&i.Sent, &i.Oldest, &i.Latest)
	return i, err
}

const takeAttempt = `-- name: TakeAttempt :one
UPDATE auth.otp_challenges AS o SET attempts = o.attempts + 1
WHERE o.id = (
    SELECT c.id FROM auth.otp_challenges AS c
    WHERE c.phone_hmac = $1 AND c.consumed_at IS NULL AND c.expires_at > now()
    ORDER BY c.created_at DESC
    LIMIT 1
  )
  AND o.attempts < $2::smallint AND o.consumed_at IS NULL AND o.expires_at > now()
RETURNING o.id, o.code_hash, o.attempts
`

type TakeAttemptParams struct {
	PhoneHmac   []byte
	MaxAttempts int16
}

type TakeAttemptRow struct {
	ID       uuid.UUID
	CodeHash []byte
	Attempts int16
}

// Counts one guess against the phone's latest open challenge, in one
// statement: concurrent guesses each take an attempt, and none is allowed
// past the limit. No row: no open challenge, or no attempts left.
func (q *Queries) TakeAttempt(ctx context.Context, arg TakeAttemptParams) (TakeAttemptRow, error) {
	row := q.db.QueryRow(ctx, takeAttempt, arg.PhoneHmac, arg.MaxAttempts)
	var i TakeAttemptRow
	err := row.Scan(&i.ID, &i.CodeHash, &i.Attempts)
	return i, err
}
