// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh.sql

package authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token_hash, user_id, family_id, replaced_by, revoked_at, expires_at, created_at FROM auth.refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.FamilyID,
		&i.ReplacedBy,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO auth.refresh_tokens (token_hash, user_id, family_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertRefreshTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.TokenHash,
		arg.UserID,
		arg.FamilyID,
		arg.ExpiresAt,
	)
	return err
}

const revokeFamily = `-- name: RevokeFamily :execrows
UPDATE auth.refresh_tokens SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

// Ends a login: every token of the family stops working.
func (q *Queries) RevokeFamily(ctx context.Context, familyID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeFamily, familyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE auth.refresh_tokens SET replaced_by = $1
WHERE token_hash = $2
  AND replaced_by IS NULL AND revoked_at IS NULL AND expires_at > now()
RETURNING user_id, family_id
`

type RotateRefreshTokenParams struct {
	ReplacedBy []byte
	TokenHash  []byte
}

type RotateRefreshTokenRow struct {
	UserID   uuid.UUID
	FamilyID uuid.UUID
}

// Compare-and-set: only a live token that was never replaced can be
// rotated, once. No row: replaced, revoked, expired or unknown.
func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RotateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, arg.ReplacedBy, arg.TokenHash)
	var i RotateRefreshTokenRow
	err := row.Scan(&i.UserID, &i.FamilyID)
	return i, err
}
