// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package authdb

import (
	"context"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, phone_hmac, phone_last4, phone_verified_at, role, created_at FROM auth.users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneHmac,
		&i.PhoneLast4,
		&i.PhoneVerifiedAt,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVerifiedUser = `-- name: UpsertVerifiedUser :one
INSERT INTO auth.users (id, phone_hmac, phone_last4, phone_verified_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (phone_hmac) DO UPDATE SET phone_verified_at = now()
RETURNING id, phone_hmac, phone_last4, phone_verified_at, role, created_at
`

type UpsertVerifiedUserParams struct {
	ID         uuid.UUID
	PhoneHmac  []byte
	PhoneLast4 string
}

// A verified phone signs in: the first time it creates the user, later
// times it only records the new verification. One user per phone.
func (q *Queries) UpsertVerifiedUser(ctx context.Context, arg UpsertVerifiedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertVerifiedUser, arg.ID, arg.PhoneHmac, arg.PhoneLast4)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneHmac,
		&i.PhoneLast4,
		&i.PhoneVerifiedAt,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
