-- +goose Up
-- Booking schema, part 1: the event catalog and the final guards that make
-- overselling impossible at the database level (invariants I1 and I4).
-- IDs are UUIDv7 generated by the application, so a service knows an ID
-- before it inserts (useful for idempotency keys and outbox events).
CREATE SCHEMA IF NOT EXISTS booking;

CREATE TABLE booking.events (
  id                      uuid        PRIMARY KEY,
  name                    text        NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
  sale_opens_at           timestamptz NOT NULL,
  verified_window_ends_at timestamptz,
  agent_lockout_ends_at   timestamptz,
  per_user_limit          smallint    NOT NULL DEFAULT 4 CHECK (per_user_limit BETWEEN 1 AND 10),
  unit_price_paise        bigint      NOT NULL CHECK (unit_price_paise > 0),
  status                  text        NOT NULL DEFAULT 'SCHEDULED'
                          CHECK (status IN ('SCHEDULED', 'OPEN', 'FROZEN', 'SOLD_OUT', 'CLOSED')),
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  CHECK (verified_window_ends_at IS NULL OR verified_window_ends_at >= sale_opens_at),
  CHECK (agent_lockout_ends_at IS NULL OR agent_lockout_ends_at >= sale_opens_at)
);

-- Final guard for quantity-mode sales. Confirmations use a conditional
-- UPDATE (sold + qty <= capacity) so they fail cleanly with zero rows; the
-- CHECK constraint is the backstop that turns any bug into an error, never
-- into an oversold event.
CREATE TABLE booking.event_inventory (
  event_id   uuid        PRIMARY KEY REFERENCES booking.events (id) ON DELETE CASCADE,
  capacity   integer     NOT NULL CHECK (capacity > 0),
  sold       integer     NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT no_oversell CHECK (sold >= 0 AND sold <= capacity)
);

-- Per-user cap guard (invariant I4), written in the same transaction as the sale.
CREATE TABLE booking.user_event_purchases (
  event_id   uuid        NOT NULL REFERENCES booking.events (id) ON DELETE CASCADE,
  user_id    uuid        NOT NULL,
  qty        smallint    NOT NULL CHECK (qty BETWEEN 0 AND 10),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (event_id, user_id)
);

-- +goose Down
DROP TABLE IF EXISTS booking.user_event_purchases;
DROP TABLE IF EXISTS booking.event_inventory;
DROP TABLE IF EXISTS booking.events;
