-- +goose Up
-- Booking schema, part 2 (Phase 3): bookings and their state machine, the
-- public API's idempotency keys, and the two messaging tables every service
-- schema has: the transactional outbox and the processed-message log.
-- IDs are UUIDv7 generated by the application, as in part 1.

-- A booking is one buyer's purchase of one hold, from checkout to its end.
-- Its status follows the state machine in design doc 7.2; the trigger below
-- refuses any other move, so a bug cannot, for example, un-refund a booking.
CREATE TABLE booking.bookings (
  id               uuid        PRIMARY KEY,
  event_id         uuid        NOT NULL REFERENCES booking.events (id),
  user_id          uuid        NOT NULL,
  hold_id          uuid        NOT NULL UNIQUE,  -- at most one booking per hold
  qty              smallint    NOT NULL CHECK (qty BETWEEN 1 AND 10),
  amount_paise     bigint      NOT NULL CHECK (amount_paise > 0), -- integer paise, never float
  status           text        NOT NULL DEFAULT 'PENDING_PAYMENT'
                   CHECK (status IN ('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'REFUND_REQUIRED', 'REFUNDED')),
  payment_deadline timestamptz NOT NULL,
  intent_id        uuid,                         -- payment-svc's intent, once created
  version          integer     NOT NULL DEFAULT 0, -- incremented by every status change
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- The deadline job scans only bookings still waiting for payment.
CREATE INDEX bookings_pending_deadline_idx ON booking.bookings (payment_deadline)
  WHERE status = 'PENDING_PAYMENT';
CREATE INDEX bookings_user_idx ON booking.bookings (user_id, created_at DESC);

-- +goose StatementBegin
CREATE FUNCTION booking.check_booking_transition() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status = OLD.status THEN
    RETURN NEW;
  END IF;
  IF (OLD.status, NEW.status) IN (
       ('PENDING_PAYMENT', 'CONFIRMED'),
       ('PENDING_PAYMENT', 'CANCELLED'),
       ('PENDING_PAYMENT', 'REFUND_REQUIRED'),
       ('CANCELLED',       'CONFIRMED'),        -- a late capture the guards accept
       ('CANCELLED',       'REFUND_REQUIRED'),  -- a late capture the guards refuse
       ('REFUND_REQUIRED', 'REFUNDED')) THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'booking %: % -> % is not a valid transition', OLD.id, OLD.status, NEW.status
    USING ERRCODE = 'check_violation';
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER bookings_status_transition
  BEFORE UPDATE OF status ON booking.bookings
  FOR EACH ROW EXECUTE FUNCTION booking.check_booking_transition();

-- Stripe-style idempotency for the public API (design doc 9.5): the first
-- request with a key records IN_PROGRESS; a retry with the same key and the
-- same request gets the stored response, and with a different request a 422.
CREATE TABLE booking.idempotency_keys (
  user_id       uuid        NOT NULL,
  idem_key      text        NOT NULL CHECK (length(idem_key) BETWEEN 8 AND 255),
  request_hash  bytea       NOT NULL CHECK (length(request_hash) = 32), -- SHA-256 of method, path and body
  status        text        NOT NULL DEFAULT 'IN_PROGRESS' CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
  booking_id    uuid,
  response_code smallint,
  response_body jsonb,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, idem_key),
  CHECK (status = 'IN_PROGRESS' OR (response_code IS NOT NULL AND response_body IS NOT NULL))
);

-- The transactional outbox: an event is written in the same transaction as
-- the state change it describes, and a relay publishes it to Kafka later.
-- Either both happen or neither does: no dual writes.
CREATE TABLE booking.outbox (
  id           bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  event_id     uuid        NOT NULL UNIQUE, -- the ce_id header: consumers deduplicate on it
  topic        text        NOT NULL,
  aggregate_id uuid        NOT NULL,        -- the Kafka message key (the booking ID)
  event_type   text        NOT NULL,        -- the ce_type header, e.g. booking.confirmed.v1
  payload      bytea       NOT NULL,        -- a protobuf message from proto/holdfast/events/v1
  headers      jsonb       NOT NULL DEFAULT '{}', -- traceparent, captured when the event was written
  created_at   timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz
);
CREATE INDEX outbox_unpublished_idx ON booking.outbox (id) WHERE published_at IS NULL;

-- Messages a consumer has already applied, recorded in the same transaction
-- as their effect: a redelivered message finds its row and changes nothing.
CREATE TABLE booking.processed_messages (
  consumer     text        NOT NULL,
  message_id   text        NOT NULL, -- the ce_id header of the Kafka message
  processed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (consumer, message_id)
);

-- +goose Down
DROP TABLE IF EXISTS booking.processed_messages;
DROP TABLE IF EXISTS booking.outbox;
DROP TABLE IF EXISTS booking.idempotency_keys;
DROP TRIGGER IF EXISTS bookings_status_transition ON booking.bookings;
DROP FUNCTION IF EXISTS booking.check_booking_transition();
DROP TABLE IF EXISTS booking.bookings;
